AllCops:
  Exclude:
    - vendor/**/*
    - examples/**/vendor/**/*
    - bin/**/*
  TargetRubyVersion: 2.5

inherit_from: .rubocop_todo.yml

Style/IfUnlessModifier:
  Enabled: false

Style/ExtendSelf:
  Enabled: false