AllCops:
  TargetRubyVersion: 2.2.0
  Exclude:
    - vendor/**/*
    - examples/**/vendor/**/*
    - bin/**/*

Metrics:
  Enabled: false

Metrics/LineLength:
  Max: 512

Style/Documentation:
  Enabled: false

inherit_from: .rubocop_todo.yml
