require 'slack-ruby-bot/commands/command_hooks'
require 'slack-ruby-bot/commands/base'
require 'slack-ruby-bot/commands/about'
require 'slack-ruby-bot/commands/help'
require 'slack-ruby-bot/commands/hi'
require 'slack-ruby-bot/commands/unknown'
